# Generated by Django 5.2.5 on 2025-08-25 08:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), editable=False, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
