# Generated by Django 5.2.5 on 2025-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0002_alter_movie_rating_avg_alter_movie_rating_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer",
            field=models.URLField(blank=True),
        ),
    ]
