# Generated by Django 5.2.5 on 2025-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0003_movie_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration_min",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(blank=True),
        ),
    ]
