# Generated by Django 5.2.5 on 2025-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0004_alter_movie_duration_min_alter_movie_poster_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration_min",
            field=models.IntegerField(blank=True, default=""),
        ),
    ]
