# Generated by Django 5.2.5 on 2025-08-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0005_alter_movie_duration_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration_min",
            field=models.CharField(blank=True, default="TBA"),
        ),
    ]
