# Generated by Django 5.2.5 on 2025-08-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0006_alter_movie_duration_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="app_muvix.movie",
            ),
        ),
    ]
