# Generated by Django 5.2.5 on 2025-08-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0007_alter_show_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="starts_at",
            field=models.TimeField(null=True),
        ),
    ]
