# Generated by Django 5.2.5 on 2025-08-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0008_show_date_alter_show_starts_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="movie",
            name="stars",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
