# Generated by Django 5.2.5 on 2025-08-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0009_movie_director_movie_genre_movie_stars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theater",
            name="cols",
        ),
        migrations.RemoveField(
            model_name="theater",
            name="rows",
        ),
    ]
