# Generated by Django 5.2.5 on 2025-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0010_remove_theater_cols_remove_theater_rows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
