# Generated by Django 5.2.5 on 2025-09-01 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0011_alter_show_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="app_muvix.theater",
            ),
        ),
        migrations.AlterField(
            model_name="theater",
            name="seat_map_json",
            field=models.TextField(),
        ),
    ]
