# Generated by Django 5.2.5 on 2025-09-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0012_alter_show_theater_alter_theater_seat_map_json"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theater",
            old_name="seat_map_json",
            new_name="seat_map",
        ),
    ]
