# Generated by Django 5.2.5 on 2025-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0013_rename_seat_map_json_theater_seat_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=7),
            preserve_default=False,
        ),
    ]
