# Generated by Django 5.2.5 on 2025-09-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0014_show_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="hold_expires_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="app_muvix.show",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservedseat",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_seats",
                to="app_muvix.show",
            ),
        ),
    ]
