# Generated by Django 5.2.5 on 2025-09-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0015_remove_reservation_hold_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rating_avg",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="watchlist",
        ),
    ]
