# Generated by Django 5.2.5 on 2025-09-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_muvix",
            "0016_remove_movie_rating_avg_remove_movie_rating_count_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
