# Generated by Django 5.2.5 on 2025-09-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_muvix", "0017_delete_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservedseat",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_seats",
                to="app_muvix.reservation",
            ),
        ),
    ]
